INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('103', '200240', '2023-03-18', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('107', '190205', '2023-04-07', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('116', '200234', '2023-04-15', '35');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('119', '202035', '2023-04-18', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('106', '202040', '2023-04-06', '35');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('102', '200234', '2023-03-17', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('120', '200229', '2023-04-18', '35');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('105', '190212', '2023-04-05', '35');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('101', '200204', '2023-02-15', '35');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('121', '201504', '2023-04-18', '35');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('109', '190215', '2023-04-11', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('122', '210401', '2023-04-18', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('115', '191429', '2023-04-14', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('125', '191455', '2023-04-19', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('110', '200912', '2023-04-11', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('111', '180815', '2023-04-11', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('104', '202608', '2023-04-04', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('112', '202805', '2023-04-11', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('123', '211135', '2023-04-18', '35');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('117', '211806', '2023-04-17', '35');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('118', '190328', '2023-04-17', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('108', '181505', '2023-04-09', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('113', '192909', '2023-04-12', '65');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('124', '201128', '2023-04-18', '35');
INSERT INTO `dining_management_system`.`payments` (`Transaction_ID`, `Student_ID`, `Date_of_transaction`, `Price`) VALUES ('114', '180629', '2023-04-12', '35');

UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T101' WHERE (`Transaction_ID` = '101');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T102' WHERE (`Transaction_ID` = '102');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T103' WHERE (`Transaction_ID` = '103');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T104' WHERE (`Transaction_ID` = '104');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T105' WHERE (`Transaction_ID` = '105');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T106' WHERE (`Transaction_ID` = '106');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T107' WHERE (`Transaction_ID` = '107');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T108' WHERE (`Transaction_ID` = '108');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T109' WHERE (`Transaction_ID` = '109');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T110' WHERE (`Transaction_ID` = '110');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T111' WHERE (`Transaction_ID` = '111');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T112' WHERE (`Transaction_ID` = '112');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T113' WHERE (`Transaction_ID` = '113');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T114' WHERE (`Transaction_ID` = '114');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T115' WHERE (`Transaction_ID` = '115');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T116' WHERE (`Transaction_ID` = '116');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T117' WHERE (`Transaction_ID` = '117');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T118' WHERE (`Transaction_ID` = '118');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T119' WHERE (`Transaction_ID` = '119');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T120' WHERE (`Transaction_ID` = '120');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T121' WHERE (`Transaction_ID` = '121');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T122' WHERE (`Transaction_ID` = '122');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T123' WHERE (`Transaction_ID` = '123');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T124' WHERE (`Transaction_ID` = '124');
UPDATE `dining_management_system`.`payments` SET `Transaction_ID` = 'T125' WHERE (`Transaction_ID` = '125');

UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch' WHERE (`Transaction_ID` = 'T101');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch' WHERE (`Transaction_ID` = 'T106');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch' WHERE (`Transaction_ID` = 'T114');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch' WHERE (`Transaction_ID` = 'T116');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch' WHERE (`Transaction_ID` = 'T123');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Dinner' WHERE (`Transaction_ID` = 'T124');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Dinner' WHERE (`Transaction_ID` = 'T121');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Dinner' WHERE (`Transaction_ID` = 'T120');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Dinner' WHERE (`Transaction_ID` = 'T117');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Dinner' WHERE (`Transaction_ID` = 'T105');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T102');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T103');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T104');

UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T125');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T122');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T119');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T118');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T115');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T113');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T112');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T111');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T107');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T108');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T109');
UPDATE `dining_management_system`.`payments` SET `Meal_type` = 'Lunch and Dinner' WHERE (`Transaction_ID` = 'T110');
